# Generated by Django 4.0.3 on 2022-04-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfshandler', '0002_hevdepartures'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HevDepartures',
            new_name='HevDeparture',
        ),
    ]
