# Generated by Django 4.0.3 on 2022-04-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtfshandler', '0004_rename_departuretime_hevdeparture_departure_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hevdeparture',
            old_name='departure_time',
            new_name='departureTime',
        ),
    ]
